[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
 "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
 viaIR = true
optimizer = true
optimizer_runs = 200